/**
 * Copyright 2024 Pax8, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import chalk from "chalk";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

export interface InitTenantInput {
  tenantId: string;
  name: string;
  environmentUrl: string;
}

export async function storeClientSecretWithFallback(
  partnerTenantId: string,
  partnerClientId: string,
  clientSecret: string
): Promise<{ partnerClientSecret: string; clientSecretCreated: boolean }> {
  try {
    const { storeCredentials } = await import("../lib/auth.js");
    await storeCredentials(partnerClientId, clientSecret, partnerTenantId);
    console.log(chalk.green("   ✓ Secret stored securely in OS keychain"));
    return {
      partnerClientSecret: clientSecret,
      clientSecretCreated: true,
    };
  } catch {
    // Keychain failed, save to .env file automatically
    const envPath = resolve(process.cwd(), ".env");
    const envContent = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";

    // Check if PARTNER_CLIENT_SECRET already exists
    if (envContent.includes("PARTNER_CLIENT_SECRET=")) {
      console.log(chalk.green("   ✓ Secret already configured in .env"));
      // Load the existing secret from .env into memory
      const match = envContent.match(/PARTNER_CLIENT_SECRET=(.+)/);
      return {
        partnerClientSecret: match?.[1]?.trim() || clientSecret,
        clientSecretCreated: true,
      };
    }

    const newContent =
      envContent.endsWith("\n") || envContent === ""
        ? envContent + `PARTNER_CLIENT_SECRET=${clientSecret}\n`
        : envContent + `\nPARTNER_CLIENT_SECRET=${clientSecret}\n`;
    writeFileSync(envPath, newContent, { mode: 0o600 });

    // Ensure restrictive permissions even if file existed
    if (process.platform !== "win32") {
      chmodSync(envPath, 0o600);
    } else {
      // Note: Windows doesn't support Unix file permissions
      console.log(
        chalk.dim("  Note: On Windows, use NTFS permissions to restrict .env file access")
      );
    }

    console.log(chalk.green("   ✓ Secret saved to .env (restricted permissions)"));

    // Auto-add .env to .gitignore if not already there
    const gitignorePath = resolve(process.cwd(), ".gitignore");
    if (existsSync(gitignorePath)) {
      const gitignoreContent = readFileSync(gitignorePath, "utf-8");
      if (!gitignoreContent.includes(".env")) {
        writeFileSync(gitignorePath, gitignoreContent.trimEnd() + "\n.env\n");
        console.log(chalk.green("   ✓ Added .env to .gitignore"));
      }
    } else {
      writeFileSync(gitignorePath, ".env\n");
      console.log(chalk.green("   ✓ Created .gitignore with .env"));
    }

    return {
      partnerClientSecret: clientSecret,
      clientSecretCreated: true,
    };
  }
}

export function writeInitConfigFile(
  configPath: string,
  partnerTenantId: string,
  partnerClientId: string,
  sourceEnvironmentUrl: string,
  tenants: InitTenantInput[]
): void {
  const configDir = dirname(configPath);

  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  // Generate tenant entries
  let tenantsYaml = "";
  if (tenants.length > 0) {
    for (const t of tenants) {
      tenantsYaml += `
  - tenantId: "${t.tenantId}"
    name: "${t.name}"
    environmentUrl: "${t.environmentUrl}"
    enabled: true
    tags:
      - production`;
    }
  }

  const sourceYaml = sourceEnvironmentUrl
    ? `source:
  tenantId: "${partnerTenantId}"
  environmentUrl: "${sourceEnvironmentUrl}"`
    : `# Source environment (where you develop agents)
# source:
#   tenantId: "${partnerTenantId}"
#   environmentUrl: "https://your-dev-org.crm.dynamics.com"`;

  const configContent = `# AgentSync Configuration File
# Generated by: pax8-cta init

# Partner/MSP Credentials (Azure AD App Registration)
partner:
  tenantId: "${partnerTenantId}"
  clientId: "${partnerClientId}"

${sourceYaml}

# Target tenants (where agents will be deployed)
# Add tenants here or re-run 'pax8-cta init' to discover them via GDAP
tenants:${tenantsYaml || " []"}
# Example:
#   - tenantId: "customer-tenant-guid"
#     name: "Contoso"
#     environmentUrl: "https://contoso.crm.dynamics.com"
#     enabled: true
`;

  writeFileSync(configPath, configContent);
  console.log(chalk.green(`  ✓ Configuration saved to ${configPath}`));
}
